### ISSUE TITLE
client example does not work: unknown field 'ServerMessages'

### ISSUE THREAD

**Issue by meisterluk** [unistack-org/go-rfb#4]
The current example code gives

```
# command-line-arguments
./client_main.go:30:17: unknown field 'ServerMessages' in struct literal of type vnc.ClientConfig
```

because of

https://github.com/vtolstov/go-vnc/blob/f6acfdfdad844a293a5670d8f719cb3ec5c31368/example/client/main.go#L30

to make it work, you need change line 30 to

```
Messages:         vnc.DefaultServerMessages,
```

**Comment by vtolstov** [comment]
sorry, miss that. i'm try to fixup all stuff and write tests.

**Comment by vtolstov** [comment]
thanks!
