### ISSUE TITLE
server example show black screen in client

### ISSUE THREAD

**Issue by muka** [unistack-org/go-rfb#6]
Hi,
great library!  

I am trying to get the server example to work, however I just see a black screen on my client. 

To my understanding, the `im` variable is set at every timer tick but it is not passed to the server channel (?) 

Thank you
Regards

**Comment by vtolstov** [comment]
yes, example may be from bradfitz and after some rewriting vnc package i'm forget to fix it. thanks

**Comment by vtolstov** [comment]
i'm fix server example, please check it now.

**Comment by muka** [comment]
Works great! 

I will try also different encoding (there are other repos implementing also video codec encodings), hope to be able to provide back  some more examples..

Thank you

**Comment by vtolstov** [comment]
What kind of encoding do you mean?

**Comment by muka** [comment]
I seen the issue #5 which refer to this repo that seems to support more encodings https://github.com/amitbet/vncproxy/blob/master/proxy/proxy.go#L133

The additional encoding are those (just based on their names, sorry if wrong)

- EncLedStatePseudo
- RREEncoding
- ZLibEncoding
- ZRLEEncoding
- CoRREEncoding
- HextileEncoding

**Comment by vtolstov** [comment]
Thanks, yes i think about adding some more encodings, but i want not to copy all of them, but only really useful. For web - tightpng is the best. For standalone clients - mostly used in this order:
EncZRLE EncCopyRect EncJRLE EncJPEG EncTRLE EncZlib EncHextile EncRRE EncRaw EncClientRedirect EncCursorPseudo EncDesktopSizePseudo
so may be in the near feature i'm add some more of them and other pseudo encodings
